name: test-project-summary-slack

on:
  pull_request:
    branches:
      - main

jobs:
  test-slack-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'

      - name: Test input validation and period parsing
        shell: bash
        env:
          INPUT_SLACK_CHANNELS: 'C123456789'
          INPUT_OUTPUTS: 'slack'
          INPUT_NOTIFICATION_SLACK_CHANNEL: 'C123456789'
          INPUT_SLACK_BOT_TOKEN: 'dummy'
          INPUT_SLACK_TEAM_ID: 'dummy'
          INPUT_ANTHROPIC_API_KEY: 'dummy'
          INPUT_PERIOD: 'last-7-days'
          INPUT_TEMPLATE: 'weekly-check'
        run: |
          bash project-summary/scripts/validate-inputs.sh

      - name: Test period parsing
        id: parse-period
        shell: bash
        env:
          INPUT_PERIOD: 'last-7-days'
        run: |
          bash project-summary/scripts/parse-period.sh

      - name: Install Slack data collection dependencies
        shell: bash
        run: |
          cd project-summary/scripts
          npm install

      - name: Test Slack data collection script
        shell: bash
        env:
          INPUT_SLACK_BOT_TOKEN: 'dummy'
          INPUT_SLACK_CHANNELS: 'C123456789'
          START_DATE: ${{ steps.parse-period.outputs.START_DATE }}
          END_DATE: ${{ steps.parse-period.outputs.END_DATE }}
        run: |
          # Test script existence and basic structure
          if [ -f project-summary/scripts/collect-slack-data.js ]; then
            echo "✓ collect-slack-data.js exists"
            node -c project-summary/scripts/collect-slack-data.js && echo "✓ Script syntax is valid" || echo "✗ Script has syntax errors"
          else
            echo "✗ collect-slack-data.js not found"
            exit 1
          fi
